# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleaOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(unique=True)),
                ('reddit_username', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleaTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(unique=True)),
                ('stat_fgpct100', models.PositiveIntegerField(default=0)),
                ('stat_ftpct100', models.PositiveIntegerField(default=0)),
                ('stat_3pt', models.PositiveIntegerField(default=0)),
                ('stat_reb', models.PositiveIntegerField(default=0)),
                ('stat_stl', models.PositiveIntegerField(default=0)),
                ('stat_blk', models.PositiveIntegerField(default=0)),
                ('stat_ast', models.PositiveIntegerField(default=0)),
                ('stat_to', models.PositiveIntegerField(default=0)),
                ('stat_pts', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.FleaLeague')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.FleaOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
