# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flealeague',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.RedditLeagueDivision'),
        ),
        migrations.AlterField(
            model_name='redditleaguedivision',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.RedditLeague'),
        ),
    ]
